### ISSUE TITLE
"App\Models\FlexiblePage" does not exist.

### ISSUE THREAD

**Issue by mialyGit** [statikbe/laravel-filament-flexible-content-blocks#14]
![Capture d’écran (23)](https://github.com/statikbe/laravel-filament-flexible-content-blocks/assets/50203282/03fbd170-b49c-4ea2-a48d-6fa48524c87f)

I have this above error when clicking in Content > Add block > Text(+image)
![Capture d’écran (27)](https://github.com/statikbe/laravel-filament-flexible-content-blocks/assets/50203282/2d175ab8-272f-4626-8ddf-5d98bcdb5d70)

**Comment by sten** [comment]
@mialyGit I think this is related to the config file:
```
'overview_models' => [
        //TODO remove & document
        'App\Models\FlexiblePage',
        'App\Models\TranslatableFlexiblePage',
    ],

    'call_to_action_models' => [
        'App\Models\FlexiblePage',
        'App\Models\TranslatableFlexiblePage',
    ],
```

Both arrays should be empty. This is test code that got stuck there. I will remove them in the next release. Please, replace those classes with your models.

**Comment by sten** [comment]
@mialyGit thanks! I am still working on more detailed documentation. How did you find it?

I made a new release with a cleaned up config file.

**Comment by mialyGit** [comment]
I see it very good package
but please give more details documentation about translatable fields in form

**Comment by sten** [comment]
What issues are you having with the translatable fields? Normally there is a helper text that shows if a field is translatable.

**Comment by mialyGit** [comment]
There 's no issue but I would only more documentation , ...
but could you give example of code if I want to create my own custom block  please ?

**Comment by sten** [comment]
@mialyGit OK! I will work on the docs. It is quite easy though, just create a class and extend from 
`Statikbe\FilamentFlexibleContentBlocks\ContentBlocks\AbstractContentBlock` and implement all functions. Then register your new block class in the config `default_flexible_blocks` var or in your model.
