### ISSUE TITLE
Im getting Call to undefined method App\Models\Page::registerContentBlocks()

### ISSUE THREAD

**Issue by Sebastiangperez** [statikbe/laravel-filament-flexible-content-blocks#26]
I just copy the exact example but im getting this error 

Call to undefined method App\Models\Page::registerContentBlocks() 
do you know why ??

Using Filament 3 and Laravel 10

**Comment by sten** [comment]
This is defined in HasDefaultContentBlocksTrait.
Normally the example Page class should import and use this trait. 
Can you check? Thanks!

**Comment by Sebastiangperez** [comment]
Question , this package is compatible with Filament Version 3 ? because im having a lot of problems with interfaces , im using one of those examples from your example folder ? is that outdated ?
It will be nice if in the documentation you could add step by step how to add your model interfaces and uses or namespace , seems like actually is very vague.

**Comment by sten** [comment]
@Sebastiangperez Yes it is compatible with Filament v3.

I am planning to setup a repo with a sample laravel project, that I can also use for testing. I will set it up based on the sample code so I can validate it again.

With what are you stuck?

**Comment by sten** [comment]
@Sebastiangperez We have created a sample project https://github.com/statikbe/laravel-filament-package-sampler
There is also a db seeder to seed some example pages.
