### ISSUE TITLE
SlugField::create() error traslation

### ISSUE THREAD

**Issue by albertocfh** [statikbe/laravel-filament-flexible-content-blocks#27]
Hi,
I am testing your plugin and have encountered in a bug (I think). 
I created a Page model and its corresponding Resource for Filamentphp. It gives me an error when saving, saying 'Call to undefined method App\Models\Page::setTranslation()'.

The problem seems to be triggered by the SlugField::create() field inside the Resource class.

**Comment by sten** [comment]
@albertocfh Are you using translated fields?

**Comment by albertocfh** [comment]
@sten no i don't put the translated field trait.

This my model code

`class Page extends Model implements HasContentBlocks, HasHeroImageAttributes, HasIntroAttribute, HasMedia, HasMediaAttributes, HasOverviewAttributes, HasPageAttributes, HasSEOAttributes, Linkable
{
    use HasAuthorAttributeTrait;
    use HasDefaultContentBlocksTrait;
    use HasFactory;
    use HasHeroImageAttributesTrait;
    use HasIntroAttributeTrait;
    use HasOverviewAttributesTrait;
    use HasPageAttributesTrait;
    use HasSEOAttributesTrait;
    use HasSlugAttributeTrait;

    public function getViewUrl(string $locale = null): string
    {
        //todo implement controller and add route:
        return config('app.url');
    }

    public function getPreviewUrl(string $locale = null): string
    {
        return $this->getViewUrl($locale);
    }
}`

**Comment by sten** [comment]
@albertocfh Thanks for debugging this! I did not yet get to looking into the issue.

I added a check to see if the `setTranslation` fuction exists. Can you try? I made a new release:
https://github.com/statikbe/laravel-filament-flexible-content-blocks/releases/tag/v0.2.9

**Comment by albertocfh** [comment]
@sten now is ok
Thanks

next time if is ok for you i do a pull request to fix.

**Comment by sten** [comment]
Great, thanks for reporting the issue, @albertocfh!
PRs are always welcome!
