### ISSUE TITLE
Impossible to install if using spatie/laravel-medialibrary 11

### ISSUE THREAD

**Issue by errand** [statikbe/laravel-filament-flexible-content-blocks#29]
So that's mean curent version of plugin is not compatible with the latest laravel-medialibrary?

**Comment by sten** [comment]
@errand I have not tested v11 yet. I think the migration should be simple. From the medialibrary upgrade guide it seems only the image conversion configuration should be affected. 

I have another bug fix to do and then I can try to upgrade to v11. 

PRs are welcome!

**Comment by sten** [comment]
@errand I just tested v11 out and it appears the library has been almost completely rewritten. Before the spatie/image lib used a Manipulations class that provided a convenient method that would create an image conversion from an configuration array, which was used to load the conversions in the config file. I will have to implement this myself to support the existing features.

**Comment by sten** [comment]
@errand Sorry for the delay, I will start working on the refactor next week.

**Comment by errand** [comment]
@sten , no worries. You're awesome. Hugs.

**Comment by mouuuton** [comment]
Hello @sten, thanks again for this plugin, it works like a charm. Do you think you'll be able to release an update soon?

**Comment by vonec** [comment]
i still cudnt get this working on laravel 11 and media library 11

Problem 1
    - Root composer.json requires statikbe/laravel-filament-flexible-content-blocks ^1.0 -> satisfiable by statikbe/laravel-filament-flexible-content-blocks[v1.0.0, ..., v1.0.7].
    - statikbe/laravel-filament-flexible-content-blocks[v1.0.0, ..., v1.0.7] require spatie/laravel-medialibrary ^10.0.0 -> found spatie/laravel-medialibrary[10.0.0, ..., v10.x-dev] but it conflicts with your root composer.json require (^11.4).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require statikbe/laravel-filament-flexible-content-blocks:*" to figure out if any version is installable, or "composer require statikbe/laravel-filament-flexible-content-blocks:^2.1" if you know which you need.

**Comment by sten** [comment]
@vonec I am working on a fix.

**Comment by sten** [comment]
@vonec, @mouuuton, @errand: v2.0.0 is just released with laravel 11 support. Sorry again for the delay, it has been very busy lately.

I was able to keep the conversions in the config file quite similar, upgrading should be easy.
There is now also the option to use functions in the config to do the conversions, this is probably more future proof.
