### ISSUE TITLE
Content Blocks are not working on TranslatedPage

### ISSUE THREAD

**Issue by devlokman** [statikbe/laravel-filament-flexible-content-blocks#33]
https://github.com/statikbe/laravel-filament-flexible-content-blocks/blob/3b59fe2fef3000c1eb393e5bce5e41173539edcc/src/View/Components/ContentBlocks.php#L33

i need to add here
`        foreach ($page->getTranslation('content_blocks',app()->getLocale()) as $blockData) {`

instead of
`        foreach ($page->content_blocks as $blockData) {`

to get it working for TranslatedPage Model & Controller.

Version: 0.2.12

**Comment by sten** [comment]
@devlokman That is strange. I never experienced this issue. I think your model is probably not set up properly. Normally spatie-translatable should provide the correct translated version for the `content_block` variable.

I have made an example project that should work with translatable pages. You can have a look here: https://github.com/statikbe/laravel-filament-package-sampler

Let me know if this work, so I can close this issue.

**Comment by devlokman** [comment]
Hi @sten thanks for the fast reply. Actually i have used the same Model as in sample repo

**Comment by sten** [comment]
@devlokman Where do you experience this problem? In the filament admin or in your controller?

**Comment by sten** [comment]
@devlokman Great! Good luck!

I will soon release v1.0.

**Comment by devlokman** [comment]
@sten honestly this package is more better than fabricator in my opinion. wish you all good luck and success
