### ISSUE TITLE
Image not linked until second save

### ISSUE THREAD

**Issue by buzkall** [statikbe/laravel-filament-flexible-content-blocks#44]
When using the Image or ImageBlock or TextImageBlock components, the image is uploaded and saved to the media table, but it's not linked in the content block when saving.

![1](https://github.com/user-attachments/assets/72c9553f-8483-4762-8060-4cc301a1e7d5)

If I save the resource again (without changing anything) it gets linked.

![2](https://github.com/user-attachments/assets/29a350b7-b0ab-455a-b5da-2be16872e326)

I'm using Laravel 11 and the latest version of the package

**Comment by sten** [comment]
Hi, we discovered this issue right before my holidays. I still have to make fix after I am back. 

For now you can downgrade filament to v3.3.23 or lower as a temp fix.

**Comment by Quarasique** [comment]
Any updates here?

**Comment by sten** [comment]
@Quarasique Sorry for the delay. I finally did the refactor. Try the new release v2.1.0. 
If you have published the view, please update your Cards Block. See [the upgrade guide](https://github.com/statikbe/laravel-filament-flexible-content-blocks/blob/main/UPGRADE.md) for more info.
