### ISSUE TITLE
Linking a page in a CTA

### ISSUE THREAD

**Issue by Sindoweb** [statikbe/laravel-filament-flexible-content-blocks#55]
Hey all,

I'm trying to link a type "page" in a Call To Action.
I can select the page I want to link, but when I try to go to the page that shows the CTA I get an error:

No linkable model could be found for 'App\Models\Page' in morph map. of record 2

Any idea what is going on here?

Thanks.

**Comment by sten** [comment]
Did you add the Page model to the morph map?  See https://laravel-news.com/enforcing-morph-maps-in-laravel 
The package requires the use of a morph map.

**Comment by sten** [comment]
@Sindoweb Try to add a breakpoint in `CallToActionData` on line 46 where the `LinkableModelNotFoundException` is created and check what the `$callToActionBlockData` array contains. It means that `Relation::getMorphedModel($linkableType);` returns something strange.

**Comment by sten** [comment]
@Sindoweb Could it be that this is old data from before you added the morph map? If the morph map is set, the `cta_model` variable should be `page`.

Can you delete the CTA and re-create it?

**Comment by sten** [comment]
@Sindoweb It's a bit hard to debug like this. Can you make an example repo or can I access the code?

**Comment by sten** [comment]
@Sindoweb Great to hear you fixed it.
